# -*- coding: utf-8 -*-
"""Random forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zeLn2ym_AHmFkSLALRtU1hBRyCQC11OR
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""importing dataset"""

dataset=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/randomforest/IceCreamData.csv')
dataset.head(5)

"""Splitting dataset as X and Y"""

X=dataset['Temperature'].values
Y=dataset['Revenue'].values

print(X)

print(Y)

"""splitting dataset as training and test data"""

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.05,random_state=0)

"""Training the model"""

from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train.reshape(-1,1), y_train.reshape(-1,1))

"""making prediction"""

y_pred = regressor.predict(X_test.reshape(-1,1))

df = pd.DataFrame({'Real Values':y_test.reshape(-1), 'Predicted Values':y_pred.reshape(-1)})
df

"""Visualising trained model"""

# # Visualising the Random Forest Regression Results  
X_grid = np.arange(min(X), max(X), 0.01)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X_test, y_test, color = 'red')
plt.scatter(X_test, y_pred, color = 'green')
plt.title('Random Forest Regression')
plt.xlabel('Temperature')
plt.ylabel('Revenue')
plt.show()

plt.plot(X_grid, regressor.predict(X_grid), color = 'black')
plt.title('Random Forest Regression')
plt.xlabel('Temperature')
plt.ylabel('Revenue')
plt.show()