# -*- coding: utf-8 -*-
"""Simple Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hpTzWciTd2T550bjjSHXINbBANM-_D6E

Importing Libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as  pd

"""Importing dataset"""

dataset=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/simple linear regression/Salary_Data.csv')

dataset.head(5)

"""Splitting dataset in X and Y
experience -> X
salary -> Y
"""

X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,1].values

print(X)

print(Y)

"""Splitting the dataset in training and testing"""

from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(X,Y,test_size=1/3, random_state=0)

"""training the model"""

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(train_x,train_y)

"""Visualisation of training and testing data"""

# Visualizing the Training set results
viz_train = plt
viz_train.scatter(train_x, train_y, color='red')
viz_train.plot(train_x, regressor.predict(train_x), color='blue')
viz_train.title('Salary VS Experience (Training set)')
viz_train.xlabel('Year of Experience')
viz_train.ylabel('Salary')
viz_train.show()

# Visualizing the Test set results
viz_test = plt
viz_test.scatter(test_x, test_y, color='red')
viz_test.plot(train_x, regressor.predict(train_x), color='blue')
viz_test.title('Salary VS Experience (Test set)')
viz_test.xlabel('Year of Experience')
viz_test.ylabel('Salary')
viz_test.show()

"""Predicting the value"""

y_pred=regressor.predict(test_x)

print(y_pred)

print("Predicted salary: ", regressor.predict([[2.4]]))